api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import permissions
from rest_framework.authtoken import views

from .views_LIKES_AND_COMMENTS import LikeListView, CommentList
from .views_MSG import MessagesViewSet, MsgSearchViewSet, MsgLoadView
from .views_USER import UserViewSet, UserList
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = 'api'

# APPEND_SLASH=False
router = DefaultRouter()
router.register('msg', MessagesViewSet)
router.register('msg_search', MsgSearchViewSet)
router.register('users_vset', UserViewSet)

# You cannot add generic Views in routers
# router.register('msg_load', MsgLoadView, basename="Message")

# urlpatterns += router.urls
# if config.DEV:
#     urlpatterns.append(path())

# порядок важен, частный случай выше
urlpatterns = [
    # ROUTER VSETS
    path('', include(router.urls)),

    path('msg_load/', MsgLoadView.as_view(), name='msg_load'),
    path('users/<str:username>/', UserList.as_view(), name='msg_users'),
    path('likes_list', LikeListView.as_view(), name='likes_list'),
    path('comments_list', CommentList.as_view(), name='comments_list'),

    # auth; get token by login and pass, returns token
    path('api-token-auth/', views.obtain_auth_token),

    # swagger and schema
    path('swagger', TemplateView.as_view(template_name='api/swagger-ui.html',
                                         extra_context={'schema_url': 'openapi-schema'}), name='swagger-ui'),
    path('openapi', get_schema_view(
            title="My Project",
            description="API for all things …",
            version="1.0.0",
            permission_classes=(permissions.AllowAny,),
            # public=True,
        ), name='openapi-schema'),

]

# JWT
urlpatterns += [
    path('jwt/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwt/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

django1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.auth import views

from core.views import core_auth
from django1.settings import ADMIN_PATH
from home_page.views import admin_old_page

# ORDER IS IMPORTANT

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_page'),

    # hide admin
    # path('admin/', admin_old_page, name='admin_old'),
    # path(ADMIN_PATH + '/', admin.site.urls, name='admin_page'),

    path('polls/', include('polls.urls'), name='polls'),
    path('', include('home_page.urls'), name='home'),
    path('simplesite1/', include('simplesite1_bstrap.urls')),
    path('blog/', include('blog.urls')),
    path('people/', include('people.urls')),
    path('orders/', include('myshop_orders.urls', namespace='orders')),
    path('cart/', include('myshop_cart.urls', namespace='cart')),
    path('shop/', include('myshop.urls', namespace='shop')),
    # path('accounts/login/', views.LoginView.as_view(), name='login'),

    # C WORK
    path('anketa/', include('Anketa.urls'), name='anketa'),
    path('auth_github/', include('social_django.urls', namespace='social')),
    path('page_github/', core_auth),

    # todo!
    path('msg1/', include('FORM_MSG.urls')),

    # api root; BELOW
    # path('api/v1/', include('api.urls'), name='api'),

    # robots
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name='robots'),

    # debug tools
    path('__debug__/', include('debug_toolbar.urls')),
]

# api root; PRIVATE URL API
API_PATH = 'api/v1/'
# if settings.IS_SERVER:
#     API_PATH = settings.API_PATH
urlpatterns.append(path(API_PATH, include('api.urls', namespace='api')))

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    # custom login
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'), # default
    # path('accounts/login/', views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]


handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

# check for nginx static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL)  # media root

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    # ex: /main/
    path('', views.index, name='index'),
]

myshop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    # параметр ":category_slug" передается в функцию product_list
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return 'POST_TITLE'+self.title

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse


def index(request):
    # return HttpResponse("hi")
    return render(request, 'main/index.html', {})

# def index(request):
#     template = loader.get_template('main/index.html')
#     return HttpResponse(template.render(template, request))

# from django.http import HttpResponse
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>My Django Project</title>

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

</head>

<body>
{% block content %}
{% endblock %}
</body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
{#    <div class="header">#}
{#        <a href="{% url 'post_list' %}">GO TO BLOG</a>#}
{#        if logged?:#}
{#            <a href="{% url 'django1:admin_page' %}">ADMIN</a>#}
{#        <a href="/admin">ADMIN</a>#}
{#        <a href="/accounts">Accounts</a>#}
{#        <a href="{% url "user_list" %}">People</a>#}
{#        <a href="{% url "shop:product_list" %}">Shop</a>#}
{#     <li {% if section == "people" %}class="selected"{% endif %}> </li>#}
{#    </div>#}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <nav id="navbar" class="navbar navbar-expand-md navbar-light bg-primary">
        <div class="container">
            <a class="navbar-brand" href="#">Django project</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="nav">
                <ul class="navbar-nav ml-auto">
{#                    <li class="nav-item active">#}
{#                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
{#                    </li>#}
                    <li class="nav-item"><a class="nav-link" href="/admin">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" href="/accounts">Accounts</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url "user_list" %}">People</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url "shop:product_list" %}">Shop</a></li>

                </ul>
            </div>
        </div>
    </nav>


    <div class="content">
        {% if user.is_authenticated %}
            <h1>Hi, {{ user.get_username }}</h1>

            <div class="sidebar">
                <li>TEST</li>
                <li>TEST</li>
                <li>TEST3</li>
                <p>x</p>

            </div>
        {% else %}
            <p>Welcome, new user. Please log in.</p>
        {% endif %}

    </div>

    <footer class="footer">
        <div class="auth">
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'logout' %}">Log out</a>
        </div>
        <p>2021</p>
    </footer>

{% endblock %}