FORM_MSG/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from FORM_MSG import views, views_likes
from FORM_MSG.views_likes import UpdateLikeMix

app_name = 'form_msg'

router = DefaultRouter()
router.register('like_router', UpdateLikeMix, basename='like_router')

# # func
# urlpatterns = [
#     path('send/', views.send_msg, name='send_msg'),
#     path('edit/<int:pk>/', views.edit_msg, name='edit_msg'),
#     path('delete/<int:pk>/', views.delete_msg, name='delete_msg'),
#     path('', views.msg_list, name='msg_list'),
#     ]

# NOT DRF API
urlpatterns = [
    path('send/', views.MsgFormCreateView.as_view(), name='send_msg'),
    path('edit/<int:pk>/', views.UpdateMsgView.as_view(), name='edit_msg'),
    path('delete/<int:pk>/', views.DeleteMsgView.as_view(), name='delete_msg'),
    path('', views.MsgList.as_view(), name='msg_list'),

    # todo
    path('<int:pk>/', views.DetailMsgANDCommentView.as_view(), name='show_msg'),
    # path('<int:pk>/', views.DetailMsgView.as_view(), name='show_msg'),
    # path('<int:pk>/', views.get_msg, name='show_msg'),


    path('', include(router.urls)),
    path('like/<int:pk>/', views_likes.UpdateLikeView.as_view(), name='like'),  # dj
    # path('like/<int:pk>/', views_likes.UpdateLikeViewAPI.as_view(), name='like'), #drf


    path("signup/", views.SignUp.as_view(), name="signup"),
    path("users/<int:pk>/", views.UserDetails.as_view(), name="users_details"),

]

api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import permissions
from rest_framework.authtoken import views

from .views_LIKES_AND_COMMENTS import LikeListView, CommentList
from .views_MSG import MessagesViewSet, MsgSearchViewSet, MsgLoadView
from .views_USER import UserViewSet, UserList
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = 'api'

# APPEND_SLASH=False
router = DefaultRouter()
router.register('msg', MessagesViewSet)
router.register('msg_search', MsgSearchViewSet)
router.register('users_vset', UserViewSet)

# You cannot add generic Views in routers
# router.register('msg_load', MsgLoadView, basename="Message")

# urlpatterns += router.urls
# if config.DEV:
#     urlpatterns.append(path())

# порядок важен, частный случай выше
urlpatterns = [
    # ROUTER VSETS
    path('', include(router.urls)),

    path('msg_load/', MsgLoadView.as_view(), name='msg_load'),
    path('users/<str:username>/', UserList.as_view(), name='msg_users'),
    path('likes_list', LikeListView.as_view(), name='likes_list'),
    path('comments_list', CommentList.as_view(), name='comments_list'),

    # auth; get token by login and pass, returns token
    path('api-token-auth/', views.obtain_auth_token),

    # swagger and schema
    path('swagger', TemplateView.as_view(template_name='api/swagger-ui.html',
                                         extra_context={'schema_url': 'openapi-schema'}), name='swagger-ui'),
    path('openapi', get_schema_view(
            title="My Project",
            description="API for all things …",
            version="1.0.0",
            permission_classes=(permissions.AllowAny,),
            # public=True,
        ), name='openapi-schema'),

]

# JWT
urlpatterns += [
    path('jwt/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwt/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

django1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.auth import views

from core.views import core_auth
from django1.settings import ADMIN_PATH
from home_page.views import admin_old_page

# ORDER IS IMPORTANT

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_page'),

    # hide admin
    # path('admin/', admin_old_page, name='admin_old'),
    # path(ADMIN_PATH + '/', admin.site.urls, name='admin_page'),

    path('polls/', include('polls.urls'), name='polls'),
    path('', include('home_page.urls'), name='home'),
    path('simplesite1/', include('simplesite1_bstrap.urls')),
    path('blog/', include('blog.urls')),
    path('people/', include('people.urls')),
    path('orders/', include('myshop_orders.urls', namespace='orders')),
    path('cart/', include('myshop_cart.urls', namespace='cart')),
    path('shop/', include('myshop.urls', namespace='shop')),
    # path('accounts/login/', views.LoginView.as_view(), name='login'),

    # C WORK
    path('anketa/', include('Anketa.urls'), name='anketa'),
    path('auth_github/', include('social_django.urls', namespace='social')),
    path('page_github/', core_auth),

    # todo!
    path('msg1/', include('FORM_MSG.urls')),

    # api root; BELOW
    # path('api/v1/', include('api.urls'), name='api'),

    # robots
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name='robots'),

    # debug tools
    path('__debug__/', include('debug_toolbar.urls')),
]

# api root; PRIVATE URL API
API_PATH = 'api/v1/'
# if settings.IS_SERVER:
#     API_PATH = settings.API_PATH
urlpatterns.append(path(API_PATH, include('api.urls', namespace='api')))

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    # custom login
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'), # default
    # path('accounts/login/', views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]


handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

# check for nginx static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL)  # media root

FORM_MSG/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, ValidationError
from core.models import User
from .models import Message, Comment


class MsgForm(ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'text', 'accept_terms', 'file', 'image')
        help_texts = {'text': "Validator check this", 'name': 'Your name'}

    # clean_FIELD validation
    def clean_text(self):
        data = self.cleaned_data['text']
        if data != data.lower():
            raise ValidationError('Please use low case')
        return data

    def clean_accept_terms(self):
        data = self.cleaned_data['accept_terms']
        if not data:
            raise ValidationError('You should accept terms')
        return data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'rows': 2}),
        }


# форма регистрации
class CreationFormUser(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        # порядок полей
        fields = ("first_name", "last_name", "username", "email")

FORM_MSG/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from core.models import User
from .forms import MsgForm, CreationFormUser, CommentForm
from .models import Message, Comment

# from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

log = logging.getLogger(__name__)
log.setLevel(logging.INFO)


class UserDetails(DetailView):
    template_name = 'form_msg/USERPAGE.html'
    # context_object_name = ''
    # extra_context = 'доп данные'

    # change to context
    queryset = User.objects.all().select_related()

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk', '')

        # v1
        # Call the base implementation first to get a context
        # context = super().get_context_data(**kwargs)
        # context['msgs_data'] = Message.objects.select_related('author').values('id', 'author__username', 'text',
        #                                                                        'created_date') \
        #     .order_by('-created_date') \
        #     .filter(author__id=pk)
        # # .filter(author=self.request.user)
        # return context
        # and in template Записей: {{user.messages.count}}

        # v2
        context = super().get_context_data(**kwargs)
        query = Message.objects.select_related('author').values('id', 'author__username', 'text', 'created_date') \
            .order_by('-created_date') \
            .filter(author__id=pk)

        context['msgs_data'] = query
        context['msgs_data_count'] = query.count()
        return context

    # def get_queryset(self):
    #     pass


class SignUp(CreateView):
    form_class = CreationFormUser
    success_url = reverse_lazy("login")  # reverse_lazy("form_msg:msg_list")
    template_name = "form_msg/signup.html"


class MsgList(ListView):
    """List of messages with user likes"""
    template_name = "form_msg/msg_list.html"

    paginate_by = 2

    # queryset = Message.objects.select_related('author') \
    #     .values('id', 'author__username', 'text', 'created_date') \
    #     .order_by('-created_date')

    # [:3]
    queryset = Message.objects.select_related('author').prefetch_related('likes')

    # queryset = Message.objects.select_related('author').prefetch_related('likes') \
    #     .values('id', 'author__username', 'text', 'created_date', 'likes__user',) \
    #     .order_by('-created_date')

    # TODO move to get_queryset?
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MsgList, self).get_context_data(**kwargs)

        # msg ids which user likes
        if self.request.user.is_authenticated:
            msgs = self.queryset  # fix pagination
            # msgs = context['object_list']

            context['show_buttons'] = True
            # likes_count in template

            # not used DEBUG
            # msgs2=msgs.values('id').annotate(likes_cnt=Count('likes__id')).order_by('id')

            # OLD
            # msgs2 = Message.objects.annotate(
            #     like_id=F('likes__id'),
            #     likes_cnt=Count('likes__id')
            # ).values('id', 'likes_cnt').order_by('id')
            #
            # msgs2 = msgs.all().values('id', 'likes__user', count=Count('likes'))
            # for id, data_list in groupby(msgs2, lambda x: x.get('id')):
            #     print(f"msg id {id} : {list(data_list)}")

            # user likes msg ids
            context['user_likes'] = msgs.filter(likes__user=self.request.user.id).values_list('id', flat=True)
            print(context['user_likes'])
        return context

        # # msg ids which user likes
        # if self.request.user.is_authenticated:
        #     context['likes'] = Like.objects.filter(message__in=context['object_list'].values_list('id', flat=True),
        #                                            user=self.request.user) \
        #         .values_list('message__id', flat=True)
        #     print(context['likes'])
        # return context


# NO COMMENTS
class DetailMsgView(DetailView):
    model = Message
    template_name = 'form_msg/msg_BY_ID.html'
    context_object_name = 'msg'

    # queryset = Message.objects.select_related("author", "comments").values('id', 'author__username', 'text',
    #                                                                        'created_date')

    # values('id', 'author__username', 'text', 'created_date', 'comments__id','comments__user', 'comments__text')

    def get_queryset(self):
        return get_object_or_404(klass=Message.objects.select_related("author", "comments")
                                 .values('id', 'author__username', 'text', 'created_date'),
                                 id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Message'
        context['is_detail_msg'] = True
        context['show_edit_buttons'] = self.object.get('author__username') == self.request.user.username
        # context['show_comments'] = True
        # context['comments'] = Comment.objects.filter(message_id=self.object.get('id'))
        return context


class DetailMsgANDCommentView(CreateView):
    model = Message
    template_name = 'form_msg/msg_BY_ID.html'
    context_object_name = 'msg'
    form_class = CommentForm

    queryset = Message.objects.select_related("author", "comments").values('id', 'author__username', 'text',
                                                                           'created_date')  # may save form issue

    def get_success_url(self):
        return reverse_lazy('form_msg:show_msg', kwargs={'pk': self.kwargs['pk']})

    # def get_object(self, queryset=None):
    #     pk = self.kwargs['pk']
    #     return get_object_or_404(
    #         klass=Message.objects.select_related("author", "comments").values('id', 'author__username', 'text',
    #                                                                           'created_date'), pk=pk)

    # .values('id', 'author__username', 'text', 'created_date', 'comments__id','comments__user', 'comments__text')

    # def get_queryset(self):
    #     return get_object_or_404(klass=Message.objects.select_related("author")
    #                              .values('id', 'author__username', 'text', 'created_date'),
    #                              id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        msg = self.get_object()
        context = super().get_context_data(**kwargs)
        context['title'] = 'Message'
        context['is_detail_msg'] = True
        context['show_edit_buttons'] = msg.get('author__username') == self.request.user.username

        # context['comments'] = Comment.objects.filter(message__id=self.object.get('id')) # none err get
        context['comments'] = Comment.objects.select_related('user').filter(message__id=msg.get('id')).values(
            'user__username', 'text')
        context['show_comments'] = True
        context['msg'] = msg
        return context

    def form_valid(self, form):
        if self.request.user.is_anonymous:
            raise PermissionDenied()

        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.message = Message.objects.get(pk=self.kwargs['pk'])
        # obj.message = self.get_object()

        return super(DetailMsgANDCommentView, self).form_valid(form)


class UpdateMsgView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MsgForm

    template_name = "form_msg/msg_send.html"
    success_url = reverse_lazy('form_msg:send_msg')

    def get_object(self, *args, **kwargs):
        obj = super(UpdateMsgView, self).get_object(*args, **kwargs)
        if obj.author != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "📨 Send message form"
        context['btn_caption'] = "Send"
        context['table_data'] = Message.objects.select_related().order_by('-created_date')[:5]

        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        return super(UpdateMsgView, self).form_valid(form)


class DeleteMsgView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('form_msg:send_msg')

    # ignore confirm template
    def get(self, request, *args, **kwargs):
        # return self.post(request, *args, **kwargs)
        return self.delete(request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        obj = super(DeleteMsgView, self).get_object(*args, **kwargs)
        if obj.author != self.request.user:
            raise PermissionDenied()  # or Http404
        return obj


class MsgFormCreateView(LoginRequiredMixin, CreateView):
    form_class = MsgForm
    template_name = "form_msg/msg_send.html"
    initial = {'text': 'example'}
    success_url = reverse_lazy('form_msg:send_msg')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "📨 Send message form"
        context['btn_caption'] = "Send"
        context['table_data'] = Message.objects.select_related().order_by('-created_date')[:5]

        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        return super(MsgFormCreateView, self).form_valid(form)

    # def form_invalid(self, form):
    #     error
    #     return super(MsgFormCreateView, self).form_invalid(form)

FORM_MSG/templates/form_msg/USERPAGE.html
{% extends "form_msg/base_msg.html" %}
{% block title %} {{profile.get_full_name}} {% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
{#        row col-md-3#}
        {% include 'form_msg/user_item.html' %}

        <div class="col-md-9">

        <h1 class="p-1">User messages</h1>

            {% if msgs_data %}
                {% for msg in msgs_data %}
                    {% include 'form_msg/card_item_msg.html' %}
                {% endfor %}
            {% else %}
                Empty
            {% endif %}

{#            {% if page.has_other_pages %}#}
{#                {% include "paginator.html" with items=page paginator=paginator%}#}
{#            {% endif %}#}

        </div>
    </div>
</main>



{% endblock %}

FORM_MSG/templates/form_msg/card_item_msg.html
{#{% with request.resolver_match.view_name as view_name %} #}

<div class="card mb-4 shadow justify-content-center">
    {% if not is_get_msg %}
        <div class="card-header"><a href="{% url 'form_msg:show_msg' pk=msg.id %}">Message #{{ msg.id }}</a></div>
    {% endif %}
    {#                        max-width='400px'#}
    {#                        <img class="card-img img-fluid mx-auto" width="400px" src="https://cdn-icons-png.flaticon.com/512/342/342647.png">#}

    <div class="card-body">
        <p class="card-text">
            <strong class="d-block">{{ msg.author__username }}</strong>

            {{ msg.text|linebreaksbr }}
        </p>

        <div class="d-flex justify-content-between align-items-center">
            <p class=="text-muted">{{ msg.created_date|date:"d E Y" }}</p>
        </div>

        <div class="row justify-content-center"> {# col-md-6 offset-md-4 #}
            {% if show_edit_buttons %}

                {#                <button type="submit" class="btn btn-primary">Edit</button>#}
                {#                <button type="button" onclick="{% url 'form_msg:edit_msg' msg.id %}" class="btn btn-primary">Edit</button>#}
{#                todo edit method#}
                <a href="{{ msg.edit_url }}" class="btn btn-light">Edit</a>
                <a href="{{ msg.delete_url }}" class="btn btn-light ml-1">Delete</a>

{#                <a href="{% url 'form_msg:edit_msg' msg.id %}" class="btn btn-light">Edit</a>#}
{#                <a href="{% url 'form_msg:delete_msg' msg.id %}" class="btn btn-light ml-1">Delete</a>#}

            {% endif %}

            {#        ONLY FOR LIST#}
            {#            {% if user.is_authenticated and user_likes %}#}

            {#            {% if user_likes %} #}

{#        todo#}
            <form action="{% url 'form_msg:like' msg.id %}" method="POST">
                {% csrf_token %}

                {% if not is_detail_msg %}
                    {% if user_likes and msg.id in user_likes %}
                        <button type="submit" name="msg_id" value="{{ msg.id }}" class="btn btn-danger">Unlike
                            ({{ msg.likes_count }})
                        </button>
                    {% else %}
                        <button type="submit" name="msg_id" value="{{ msg.id }}" class="btn btn-primary">👍 Like
                            ({{ msg.likes_count }})
                        </button>
                    {% endif %}
                {% else %}
                    {#                    pass#}
                {% endif %}
            </form>
            {#            {% endif %}#}
        </div> <!-- card btns -->
    </div> <!-- card body -->
</div> <!-- card -->

FORM_MSG/templates/form_msg/msg_list.html
{% extends 'form_msg/base_msg.html' %}

{#MAY INCLUDE STATIC, CSS!!! FROM MAIN PAGE#}
{% load static %}
{% load custom_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-md-7 p-5">
            <h1 class="p-1">Messages</h1>

            {% if object_list %}
                {% for msg in object_list %}
                    {% include 'form_msg/card_item_msg.html' %}
                {% endfor %}
            {% else %}
                Empty
            {% endif %}

            {# paginator #}
            {% if page_obj.has_other_pages %}
            {% include 'form_msg/includes/paginator.html' %}
            {% endif %}

        </div>

    </div>
{% endblock %}

FORM_MSG/templates/form_msg/msg_nav.html
<nav id="navbar" class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-xl">
        <a class="navbar-brand" href="{% url 'form_msg:msg_list' %}">Messages</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="nav">
            {#bs4: ml-auto, bs5: me-auto#}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'form_msg:send_msg' %}"><b>✏ CREATE NEW</b></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'form_msg:msg_list' %}">All</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "api:msg_load" %}">API msg</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url "api:msg_users" request.user.username %}">API
                        user</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url "api:swagger-ui" %}">Swagger</a></li>
                <li class="nav-item"><a class="nav-link" href="/">index</a></li>

                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url "form_msg:users_details" request.user.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon"
                             style="width: 1em; height: 1em;vertical-align: middle;fill: currentColor;overflow: hidden;"
                             viewBox="0 0 1024 1024" version="1.1">
                            <path d="M843.282963 870.115556c-8.438519-140.515556-104.296296-257.422222-233.908148-297.14963C687.881481 536.272593 742.4 456.533333 742.4 364.088889c0-127.241481-103.158519-230.4-230.4-230.4S281.6 236.847407 281.6 364.088889c0 92.444444 54.518519 172.183704 133.12 208.877037-129.611852 39.727407-225.46963 156.634074-233.908148 297.14963-0.663704 10.903704 7.964444 20.195556 18.962963 20.195556l0 0c9.955556 0 18.299259-7.774815 18.962963-17.73037C227.745185 718.506667 355.65037 596.385185 512 596.385185s284.254815 122.121481 293.357037 276.195556c0.568889 9.955556 8.912593 17.73037 18.962963 17.73037C835.318519 890.311111 843.946667 881.019259 843.282963 870.115556zM319.525926 364.088889c0-106.287407 86.186667-192.474074 192.474074-192.474074s192.474074 86.186667 192.474074 192.474074c0 106.287407-86.186667 192.474074-192.474074 192.474074S319.525926 470.376296 319.525926 364.088889z"/>
                        </svg>
                    </a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url "login" %}"><b>Login</b></a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

FORM_MSG/templates/form_msg/msg_send.html
{% extends 'form_msg/base_msg.html' %}

{#MAY INCLUDE STATIC, CSS!!! FROM MAIN PAGE#}
{% load static %}
{% load custom_tags %}


{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
{#            <h1 class="p-1">Please complete the form</h1>#}

            {#            {% if error %}#}
            {#                <p>ERR: {{ error }}</p>#}
            {#            {% endif %}#}

            <div class="card">
                <div class="card-header">{{ title }}</div>
                <div class="card-body">

                    {#                    {% for error in form.errors %}#}
                    {#                        <div class="alert alert-danger" role="alert">#}
                    {#                            <span>❗ {{ error|capfirst }}</span>#}
                    {#                        </div>#}
                    {#                    {% endfor %}#}

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            <span style="display: flex">
                                ❗ {{ form.errors }}
                            </span>
                        </div>
                    {% endif %}

                    <form method="post" enctype="multipart/form-data">
                        {#                        CSRF#}
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row"
                                 aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}
                            </div>

                            <label for="{{ field.id_for_label }}" class="col-md-3 col-form-label text-md-right">
                                {{ field.label }}
                                {% if field.field.required %}<span class="required">*</span>{% endif %}

                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help"
                                           class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}

                            </label>

                            {# input, width9 #}
                            <div class="col-md-9">
                                {# input tag #}
                                {{ field|addclass:"form-control" }}
                            </div>

                            </div>
                        {% endfor %}

            <div class="row justify-content-center"> {# col-md-6 offset-md-4 #}
                <button type="submit" class="btn btn-primary">
                    {{ btn_caption }}
                </button>
            </div>
            </form>

        </div> <!-- card body -->
    </div> <!-- card -->

    {#    list of msgs#}
    {% if table_data %}
        <div class="table-responsive mt-4">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Author</th>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Text</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>

                <tbody>
                {% for item in table_data %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.author }}</td>
                        <td>{{ item.id }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.text }}</td>
                        <td>{{ item.created_date }}</td>

                        <td><a href="{% url 'form_msg:edit_msg' item.id %}">
                            {#                            edit#}
                            <svg id="i-edit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32"
                                 height="32" fill="none" stroke="currentcolor" stroke-linecap="round"
                                 stroke-linejoin="round" stroke-width="2">
                                <path d="M30 7 L25 2 5 22 3 29 10 27 Z M21 6 L26 11 Z M5 22 L10 27 Z"/>
                            </svg>
                        </a></td>
                        <td><a href="{% url 'form_msg:delete_msg' item.id %}">
                            {#                            delete#}
                            <svg id="i-trash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32"
                                 height="32" fill="none" stroke="currentcolor" stroke-linecap="round"
                                 stroke-linejoin="round" stroke-width="2">
                                <path d="M28 6 L6 6 8 30 24 30 26 6 4 6 M16 12 L16 24 M21 12 L20 24 M11 12 L12 24 M12 6 L13 2 19 2 20 6"/>
                            </svg>
                        </a></td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    {% endif %}

    {#    </div> <!-- col -->#}
    {#    </div> <!-- row -->#}
{% endblock %}

FORM_MSG/templates/form_msg/signup.html
{% extends "form_msg/base_msg.html" %}
{% load custom_tags %}

{% block title %}Зарегистрироваться{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'form_msg:signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}